### PR TITLE
[WIP] Add resilience examples and documentation

### PR DESCRIPTION
**Pull request by NK-Nikunj**
This PR adds easy-to-understand code snippets for the resilience modules in HPX. This PR adds in particular:

- [x] Local Resilience snippets
- [x] Distributed Resilience snippets
- [ ] README.md explaining resilience better

### CODE REVIEW

**Comment by NK-Nikunj** [comment]
@diehlpk could you check the code snippet and validate if this is what you want as an example?

**Comment by diehlpk** [comment]
Thanks, exactly what I wanted. We can add the relevant lines to the paper later.

**Comment by NK-Nikunj** [comment]
@diehlpk should I add a README here or do I explain it in the paper? The PR is complete if you want me to explain things in the paper.

**Comment by diehlpk** [comment]
> @diehlpk should I add a README here or do I explain it in the paper? The PR is complete if you want me to explain things in the paper.

Please copy parts of the code to the paper using the listings package and add some description there.

**Pull request merged**
